parameters:
    exception.codes:
        InvalidArgumentException: 400
        App\Exception\InvalidArgumentException: 400
        Doctrine\ActiveRecord\Exception\NotFoundException: 404
        App\Exception\UnauthorizedException: 401
        App\Exception\AccessDeniedException: 403
        Symlex\Exception\AccessDeniedException: 403
        Symlex\Exception\NotFoundException: 404
        Symlex\Exception\MethodNotAllowedException: 405
        App\Exception\FormInvalidException: 409
        Swift_TransportException: 503
        Exception: 500

    exception.messages:
        401: 'Unauthorized'
        402: 'Payment Required'
        403: 'Forbidden'
        404: 'Not Found'
        405: 'Method Not Allowed'
        406: 'Not Acceptable'
        407: 'Proxy Authentication Required'
        408: 'Request Timeout'
        410: 'Gone'
        500: 'Looks like something went wrong!'
        503: 'Service unavailable - check server configuration'