parameters:
    app.name: 'App'
    app.version: '1.0'
    app.url: 'http://localhost:8080/'
    app.email: 'root@localhost'
    db.host: mysql
    db.port: 3306
    db.name: web
    db.user: web
    db.password: web
    mailer.host: smtp.gmail.com
    mailer.port: 587
    mailer.encryption: tls
    mailer.username: ''
    mailer.password: ''
    mailer.auth_mode: ''