imports:
    - { resource: parameters.yml }
    - { resource: common.yml }
    - { resource: exceptions.yml }
    - { resource: rest.yml }

services:
    app:
        class: Symlex\Application\Web
        public: true

    service.session:
        class: App\Service\Session
        arguments: [ "@cache", "@model.user" ]

    router.error:
        class: App\Router\ErrorRouter
        public: true
        arguments: [ "@app", "@twig", "%exception.codes%", "%exception.messages%", "%app.debug%" ]
        calls:
            - [ setLogger, [ "@log" ] ]

    router.twig:
        class: Symlex\Router\Web\TwigRouter
        public: true
        arguments: [ "@app", "@service_container", "@twig" ]

    router.twig_default:
        class: Symlex\Router\Web\TwigDefaultRouter
        public: true
        arguments: [ "@app", "@service_container", "@twig" ]

    controller.web.index:
        public: true
        class: App\Controller\Web\IndexController